### ISSUE TITLE
Content-Type header check is not case insensitive

### ISSUE THREAD

**Issue by noresistence** [joomla-framework/oauth2#10]
### Steps to reproduce the issue

Manage to get the key `content-type` instead of `Content-Type` in `$response->headers` and send the token as `application/json`.

### Expected result

The token should be identified as `application/json` in https://github.com/joomla-framework/oauth2/blob/6a9f29d381042eb3326ced64882394cd7c477a8e/src/Client.php#L90

### Actual result

The header will not be identified correctly as content-type indicator.

According to [RFC 2616 - "Hypertext Transfer Protocol -- HTTP/1.1", Section 4.2, "Message Headers"](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2), Field names are case-insensitive.

### System information (as much as possible)

Appears on a fresh joomla install from docker image with tag "joomla:3-php7.1", as well as tag "joomla:3-php7.2", and tag "3" as of 17th of march.

### Additional comments

Fix it by ensuring the check to be case insensitive.

**Comment by zero-24** [comment]
Please see here @noresistence https://github.com/joomla-framework/oauth2/pull/11 when this fixes your issue please close here.

**Comment by zero-24** [comment]
and mark a successful test to the PR.

**Comment by noresistence** [comment]
Thank you very much, @zero-24 and @mbabker; your fix solves our problem.

The header fields are accessed in a second place, though: in refreshToken(). I submitted pull request #11 for this.
