### ISSUE TITLE
Not working and in code bags.

### ISSUE THREAD

**Issue by korenevskiy** [joomla-framework/oauth2#16]
This is my first time using OAuth, I don't understand this protocol. But I see obvious errors in the code.
Probably the cat walked on the keyboard when they wrote this class. :-)

![image](https://user-images.githubusercontent.com/6898474/120569211-209aa200-c41e-11eb-99ba-1c9088fd7aeb.png)

![image](https://user-images.githubusercontent.com/6898474/120568815-5db26480-c41d-11eb-8e90-ba1170e454e2.png)

![image](https://user-images.githubusercontent.com/6898474/120568428-825a0c80-c41c-11eb-90d1-ffbae7b4edd5.png)

**Comment by sergeytolkachyov** [comment]
@korenevskiy have you a code example for using Joomla OAuth2? How to use it...
